version: "3.9"

x-env: &env
  environment:
    - PUID=568
    - PGID=1001
    - TZ=${TZ}

x-deploy-nuc: &deploy-nuc
  deploy:
    placement:
      constraints:
        - node.hostname == nuc8-1

networks:
  default:
    name: smarthomeserver
    external: true

volumes:
  truenas-media:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=192.168.0.196"
      device: :/mnt/newton/media
  truenas-torrents:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=192.168.0.196"
      device: :/mnt/newton/media/qbit/torrents

services:
  overseerr:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - ${SERVARRDIR}/overseerr/config:/config
    restart: unless-stopped

  komga:
    <<: *deploy-nuc
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - ${SERVARRDIR}/komga/config:/config
      - /etc/timezone:/etc/timezone
      - type: volume
        source: truenas-media
        target: /data
    user: "568:1001"
    restart: unless-stopped

  radarr:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ${SERVARRDIR}/radarr/config:/config
      - type: volume
        source: truenas-media
        target: /data
    restart: unless-stopped

  prowlarr:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    volumes:
      - ${SERVARRDIR}/prowlarr/config:/config
    restart: unless-stopped

  sonarr:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ${SERVARRDIR}/sonarr/config:/config
      - type: volume
        source: truenas-media
        target: /data
    restart: unless-stopped

  readarr:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - ${SERVARRDIR}/readarr/config:/config
      - type: volume
        source: truenas-media
        target: /data
    restart: unless-stopped

  mylar3:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    ports:
      - 8090:8090
    volumes:
      - ${SERVARRDIR}/mylar3/config:/config
      - type: volume
        source: truenas-media
        target: /data
    restart: unless-stopped

  calibre:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    volumes:
      - ${SERVARRDIR}/calibre/config:/config
      - type: volume
        source: truenas-media
        target: /data
    restart: unless-stopped

  tautulli:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    volumes:
      - ${SERVARRDIR}/tautulli/config:/config
    restart: unless-stopped

  bazarr:
    <<: *env
    <<: *deploy-nuc
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - ${SERVARRDIR}/bazarr/config:/config
      - type: volume
        source: truenas-media
        target: /data
    restart: unless-stopped

  recyclarr:
    <<: *deploy-nuc
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    init: true
    user: 568:1001
    volumes:
      - ${DATADIR}/recyclarr/config:/config
    environment:
      - TZ=America/Chicago
      - CRON_SCHEDULE=@hourly
      - RECYCLARR_CREATE_CONFIG=true
      - TINI_SUBREAPER=true

  cross-seed:
    image: crossseed/cross-seed
    container_name: cross-seed
    user: 568:1001
    volumes:
        - ${DATADIR}/cross-seed/config:/config
        - type: volume
          source: truenas-torrents
          target: /torrents
        - ${DATADIR}/cross-seed/cross-seeds:/cross-seeds
    command: daemon # this enables the daemon
    restart: unless-stopped

  epic-games:
    image: charlocharlie/epicgames-freegames:latest
    container_name: epic-games
    volumes:
      - ${DATADIR}/epic-games/config:/usr/app/config
    deploy:
      resources:
        limits:
          memory: 2g

  plex-meta-manager:
    image: kometateam/kometa:develop
    container_name: plex-meta-manager
    user: 568:1001
    environment:
      - TZ=America/Chicago #optional
    volumes:
      - ${DATADIR}/plex-meta-manager/config:/config
    restart: unless-stopped

  maintainerr:
    environment:
      - TZ=America/Chicago
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: 568:1001
    volumes:
      - ${DATADIR}/maintainerr:/opt/data
    # ports:
    #   - 6246:6246
    restart: unless-stopped
