version: "3.9"

x-env: &env
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}

networks:
  default:
    name: smarthomeserver
    external: true

volumes:
  nas-media:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.0.156"
      device: :/share/Multimedia
  calibre-media:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.0.156,nolock" # nolock is required for calibre to load. Hopefully this is no longer necessary once migrated to NFSv4 server.
      device: :/share/Multimedia

services:
  overseerr:
    <<: *env
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - ${DATADIR}/overseerr/config:/config
    restart: unless-stopped

  komga:
    image: index.docker.io/gotson/komga
    container_name: komga
    volumes:
      - ${DATADIR}/komga/config:/config
      - /etc/timezone:/etc/timezone
      - type: volume
        source: nas-media
        target: /data
    user: "${PUID}:${PGID}"
    restart: unless-stopped

  nzbget:
    <<: *env
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    volumes:
      - ${DATADIR}/nzbget/config:/config
      - type: volume
        source: nas-media
        target: /data
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/ #optional
      - USER=admin #optional
      - PASS=ZXzpmZ!QTt*A6YRk #optional
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ${DATADIR}/flood-for-transmission:/flood-for-transmission
      - ${DATADIR}/transmission/config:/config
      - type: volume
        source: nas-media
        target: /data
    restart: unless-stopped

  radarr:
    <<: *env
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ${DATADIR}/radarr/config:/config
      - type: volume
        source: nas-media
        target: /data
    restart: unless-stopped

  prowlarr:
    <<: *env
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    volumes:
      - ${DATADIR}/prowlarr/config:/config
    restart: unless-stopped

  sonarr:
    <<: *env
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ${DATADIR}/sonarr/config:/config
      - type: volume
        source: nas-media
        target: /data
    restart: unless-stopped

  readarr:
    <<: *env
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - ${DATADIR}/readarr/config:/config
      - type: volume
        source: nas-media
        target: /data
    restart: unless-stopped

  mylar3:
    <<: *env
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    volumes:
      - ${DATADIR}/mylar3/config:/config
      - type: volume
        source: nas-media
        target: /data
    restart: unless-stopped

  calibre:
    <<: *env
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    volumes:
      - ${DATADIR}/calibre/config:/config
      - type: volume
        source: calibre-media
        target: /data
    restart: unless-stopped

  unpackerr:
    <<: *env
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ${DATADIR}/unpackerr/config:/etc/unpackerr/
      - type: volume
        source: nas-media
        target: /data
    restart: unless-stopped
