version: "3.9"

networks:
  default:
    name: smarthomeserver
    external: true

volumes:
    teslalogger-tmp:

services:
  teslalogger:
    image: twoscomplement/teslalogger:latest
    restart: always
    volumes:
      - ${DATADIR}/teslalogger/TeslaLogger/www:/var/www/html
      - ${DATADIR}/teslalogger/TeslaLogger/bin:/etc/teslalogger
      - ${DATADIR}/teslalogger/TeslaLogger/GrafanaDashboards/:/var/lib/grafana/dashboards/
      - ${DATADIR}/teslalogger/TeslaLogger/GrafanaPlugins/:/var/lib/grafana/plugins
      - ${DATADIR}/teslalogger/docker/teslalogger/Dockerfile:/tmp/teslalogger-DOCKER
      - teslalogger-tmp:/tmp/
#    depends_on:
#     - database
    environment:
      - TZ=America/Chicago
      - GRAFANA_PASSWORD=teslalogger
#    ports:
#      - 5010:5000

  database:
    image: mariadb:10.4.7
    restart: always
    env_file:
      - .env
    volumes:
      - ${DATADIR}/teslalogger/TeslaLogger/sqlschema.sql:/docker-entrypoint-initdb.d/sqlschema.sql
      - ${DATADIR}/teslalogger/TeslaLogger/mysql:/var/lib/mysql
#    ports:
#     - 3306:3306
    environment:
      - TZ=America/Chicago
      - MYSQL_USER=teslalogger
      - MYSQL_PASSWORD=teslalogger
      - MYSQL_DATABASE=teslalogger
      - MYSQL_ROOT_PASSWORD=teslalogger
      - GRAFANA_PASSWORD=teslalogger

  grafana:
    image: grafana/grafana:8.3.2
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=teslalogger
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=natel-discrete-panel,pr0ps-trackmap-panel,teslalogger-timeline-panel
      - GRAFANA_PASSWORD=teslalogger
      - TZ=America/Chicago
#    ports:
#      - 3000:3000
    volumes:
      - ${DATADIR}/teslalogger/TeslaLogger/bin:/etc/teslalogger
      - ${DATADIR}/teslalogger/TeslaLogger/GrafanaDashboards/:/var/lib/grafana/dashboards/
      - ${DATADIR}/teslalogger/TeslaLogger/GrafanaPlugins/:/var/lib/grafana/plugins
      - ${DATADIR}/teslalogger/TeslaLogger/GrafanaConfig/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
      - ${DATADIR}/teslalogger/TeslaLogger/GrafanaConfig/sample.yaml:/etc/grafana/provisioning/dashboards/dashboards.yml
#    depends_on:
#      - database

  webserver:
    image: twoscomplement/teslalogger-web:latest
    restart: always
    volumes:
      - ${DATADIR}/teslalogger/docker/webserver/php.ini:/usr/local/etc/php/php.ini
      - ${DATADIR}/teslalogger/TeslaLogger/www:/var/www/html
      - ${DATADIR}/teslalogger/TeslaLogger/bin:/etc/teslalogger
      - ${DATADIR}/teslalogger/docker/teslalogger/Dockerfile:/tmp/teslalogger-DOCKER
      - ${DATADIR}/teslalogger/TeslaLogger/GrafanaConfig/datasource.yaml:/tmp/datasource-DOCKER
      - teslalogger-tmp:/tmp/
#    ports:
#      - 8888:80
    environment:
      - TZ=America/Chicago
      - GRAFANA_PASSWORD=teslalogger

