version: "3.9"

# NOTE: AdGuard Home is now managed separately via adguard-standalone.yaml
# with host networking for keepalived VIP failover support.
# See keepalived/README.md for details.

networks:
  default:
    name: smarthomeserver
    external: true

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    restart: unless-stopped
    environment:
      TZ: America/Chicago
      S6_STAGE2_HOOK: sed -i -e $$d -e $$d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${DATADIR}/nginx-package-manager/data:/data
      - ${DATADIR}/nginx-package-manager/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
      start_period: 600s
    deploy:
      replicas: 2
