version: "3.9"

x-env: &env
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}

networks:
  default:
    name: smarthomeserver
    external: true
  adguard-mvl-1:
    external: true
  adguard-mvl-2:
    external: true
  adguard-mvl-3:
    external: true

volumes:
  adguard1:
  adguard2:
  adguard3:

services:
  adguard1:
    <<: *env
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    # ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp"
    #  - "443:443/tcp"
    #  - "853:853/tcp"
    #  - "784:784/udp"
    #  - "3300:3000/tcp"
    #  - "3380:80/tcp"
    volumes:
      - "adguard1:/opt/adguardhome/work"
      - "${DATADIR}/adguard/confdir:/opt/adguardhome/conf"
    networks:
      - adguard-mvl-1

  adguard2:
    <<: *env
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    # ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp"
    #  - "443:443/tcp"
    #  - "853:853/tcp"
    #  - "784:784/udp"
    #  - "3300:3000/tcp"
    #  - "3380:80/tcp"
    volumes:
      - "adguard2:/opt/adguardhome/work"
      - "${DATADIR}/adguard/confdir:/opt/adguardhome/conf"
    networks:
      - adguard-mvl-2

  adguard3:
    <<: *env
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    # ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp"
    #  - "443:443/tcp"
    #  - "853:853/tcp"
    #  - "784:784/udp"
    #  - "3300:3000/tcp"
    #  - "3380:80/tcp"
    volumes:
      - "adguard3:/opt/adguardhome/work"
      - "${DATADIR}/adguard/confdir:/opt/adguardhome/conf"
    networks:
      - adguard-mvl-3

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${DATADIR}/nginx-package-manager/data:/data
      - ${DATADIR}/nginx-package-manager/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    deploy:
      replicas: 3
      # mode: global
